// Global
export const SET_GLOBAL_NAME = "SET_GLOBAL_NAME";
export const SET_GLOBAL_THEME = "SET_GLOBAL_THEME";
export const SET_GLOBAL_LOADING = "SET_GLOBAL_LOADING";
export const SET_GLOBAL_ERROR = "SET_GLOBAL_ERROR";
export const SET_GLOBAL_PAGE_TITLE = "SET_GLOBAL_PAGE_TITLE";

const actionTypes = {
  SET_GLOBAL_NAME,
  SET_GLOBAL_THEME,
  SET_GLOBAL_LOADING,
  SET_GLOBAL_ERROR,
  SET_GLOBAL_PAGE_TITLE,
};

export default actionTypes;
